$azureUsername="AzureUserNameValue"
$azurePassword="AzurePasswordValue"
$azureTenantID="AzureTenantIDValue"
$azureSubscriptionID="AzureSubscriptionIDValue"
$deploymentID="DeploymentIDValue"
$odlId="ODLIDValue"
